server:
  port: 8678
  servlet:
    context-path: /api/v1/EmailApi
spring:
  # DB
  datasource:
    url: jdbc:postgresql://ec2-52-45-183-77.compute-1.amazonaws.com:5432/d9c6ankl5cb1gj
    driver-class-name: org.postgresql.Driver
    username: jbqryelxzccrog
    password: b3b66a13654a599aa6ee17033eb72accf472d2313a5829090f2176a2448811fc

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n"
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: DEBUG